name: Geode Mod Trail Effect  # Nombre propio del workflow

# Triggers del workflow
on:
  workflow_dispatch:   # Permite ejecución manual desde GitHub
  push:
    branches:
      - "**"         # Se ejecuta en cualquier push a cualquier rama
  pull_request:
    branches: ["main", "develop"]  # También se ejecuta en PRs a estas ramas

jobs:
  compile:
    # Estrategia de ejecución con matriz
    strategy:
      fail-fast: false  # No cancelar los demás jobs si uno falla
      matrix:
        platform:
        - name: WinBuild         # Job para Windows
          os: windows-latest

        - name: Android_x86      # Job para Android 32-bit
          os: ubuntu-latest
          target: Android32

        - name: Android_x64      # Job para Android 64-bit
          os: ubuntu-latest
          target: Android64

        - name: MacBuild         # Job para macOS
          os: macos-latest

    name: Compile on ${{ matrix.platform.name }}  # Nombre dinámico del job
    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Clona el repositorio completo

      - name: Compile Geode Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings      # Ruta de las bindings
          bindings-ref: main                # Rama de las bindings
          combine: true                     # Combina todo en un único build
          target: ${{ matrix.platform.target }}  # Target según la matriz

  package_artifacts:
    name: Package & Upload Builds
    runs-on: ubuntu-latest
    needs: ['compile']  # Espera a que termine el job de compilación

    steps:
      - name: Combine All Builds
        uses: geode-sdk/build-geode-mod/combine@main
        id: combined_build  # ID para referenciar outputs

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GeodeMod-Build           # Nombre del artifact final
          path: ${{ steps.combined_build.outputs.build-output }}  # Ruta del paquete